package com.summonerswars.SW.model;

import lombok.*;

import javax.persistence.*;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;


@Getter
@Setter
@ToString
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
@Data
@Table(name = "Skill")

public class Skill {
    //Skill Unique Identifier - AutoGenerated
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    //Skill Name. Only Accepts letters (A-Z,a-z)
    @NotNull
    @NotEmpty
    @Pattern(regexp = "^[A-Za-z]*$", message = "Insert Valid Skill")
    private String name;

    //Active Name. Only Accepts letters (A-Z,a-z)
    @NotNull
    @NotEmpty
    @Pattern(regexp = "^[A-Za-z]*$", message = "Insert Valid Active")
    private String active;

    //Relation between Tables - ManytoOne with Summoners
    @ManyToOne
    @JoinColumn(name = "summoner_id")
    private Summoner summoner;
}
