package com.summonerswars.SW.model;


import lombok.*;

import javax.persistence.*;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import java.util.List;

@Getter
@Setter
@ToString
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
@Data
@Table(name = "summoner")


public class Summoner {

    //Summoner Unique Identifier - AutoGenerated
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long Id;

    //Summoner Name. Only Accepts letters (A-Z,a-z)
    @NotNull
    @NotEmpty
    @Pattern(regexp = "^[A-Za-z]*$", message = "Insert Valid name")
    private String name;

    //Relation between Tables - OnetoMany with skills (Explanation, Table Summoners can be related to many skills but each skill is related to one Summoner)
    @OneToMany(mappedBy = "summoner")
    private List<Skill> skill;
    //Relation with Tier Enum: ONE, TWO, THREE, FOUR, FIVE
    @Enumerated(EnumType.STRING)
    private Tier tier;
}
